# Generated by Django 2.2.10 on 2020-11-23 15:02

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('id_identities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('identifier', models.CharField(help_text='Used to correlate memberships', max_length=120)),
                ('properties', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('propogate_params_to_identity', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, help_text='Account parameters to propogate to identity')),
                ('collection_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('collection_data_variance', models.BooleanField(default=False)),
                ('identity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='id_identities.VdxIdentity')),
            ],
            options={
                'verbose_name': 'Access Account',
            },
        ),
    ]
