# Generated by Django 2.2.10 on 2020-11-23 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('id_accounts', '0001_initial'),
        ('id_platforms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaccount',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='id_platforms.ViPlatform'),
        ),
        migrations.AlterUniqueTogether(
            name='viaccount',
            unique_together={('identifier', 'platform')},
        ),
    ]
