# Generated by Django 2.2.10 on 2020-11-23 15:02

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('id_identities', '0001_initial'),
        ('id_access', '0002_viaccessitemrequest_account'),
        ('id_accounts', '0001_initial'),
        ('id_platforms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', django_fsm.FSMField(default=False, max_length=50)),
                ('agent_name', models.CharField(max_length=40, unique=True)),
                ('description', models.CharField(max_length=40)),
                ('heartbeat_time', models.DateTimeField(blank=True, null=True)),
                ('health_state', models.IntegerField(default=-1)),
                ('queue_name_override', models.CharField(blank=True, max_length=80, null=True)),
                ('location', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='ViAgentPlatformInterface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface_name', models.CharField(max_length=255)),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='last_updated')),
                ('api', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('task_signature', models.CharField(max_length=255, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='id_work_agent.ViAgent')),
            ],
        ),
        migrations.CreateModel(
            name='ViAccountTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('identifier', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('properties', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('propogate_params_to_identity', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, help_text='Use this field to specify parameters that should be propogated to the owning identity.')),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='id_work_agent.ViAgentPlatformInterface')),
            ],
            options={
                'verbose_name': 'Access Object Template',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ViAgentWorkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Agent API call', max_length=128)),
                ('api_call', models.CharField(max_length=255)),
                ('celery_task', models.CharField(max_length=255)),
                ('queue', models.CharField(default='platform', max_length=128)),
                ('all_tasks_successful', models.BooleanField(default=False)),
                ('complete', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('task_parameters', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('pooling_time', models.IntegerField(default=5)),
                ('trigger_platform_collection', models.BooleanField(default=False, help_text='Perform a platform collection on complete if no other platform tasks pending')),
                ('agent_workorders', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('exception', models.TextField(blank=True, null=True)),
                ('server_pk_subset', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('complete_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('access_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_work_orders', to='id_access.ViAccessItem')),
                ('identity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_work_orders', to='id_identities.VdxIdentity')),
                ('identity_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_work_orders', to='id_accounts.ViAccount')),
                ('platform', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_work_orders', to='id_platforms.ViPlatform')),
            ],
            options={
                'unique_together': {('task_parameters', 'complete', 'complete_time', 'name', 'api_call', 'celery_task', 'queue', 'platform', 'identity')},
            },
        ),
    ]
