# Generated by Django 2.2.10 on 2020-11-23 15:02

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_celery_beat', '0012_periodictask_expire_seconds'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViPlatform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('properties', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('title', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=40)),
                ('generate_new_accounts', models.BooleanField(default=False, help_text='Allows collections to generate new Accounts')),
                ('generate_new_access_items', models.BooleanField(default=False, help_text='Allows collections to generate new Entitlements')),
                ('collection_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='platform_collections', to='django_celery_beat.PeriodicTask')),
            ],
        ),
    ]
