# Generated by Django 2.2.10 on 2020-11-23 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('id_work_agent', '0001_initial'),
        ('id_platforms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='viplatform',
            name='default_account_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='platforms', to='id_work_agent.ViAccountTemplate'),
        ),
        migrations.AddField(
            model_name='viplatform',
            name='interface',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='platforms', to='id_work_agent.ViAgentPlatformInterface'),
        ),
    ]
