# Generated by Django 2.2.10 on 2020-12-03 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('id_work_agent', '0001_initial'),
        ('id_accounts', '0001_initial'),
        ('id_platforms', '0001_initial'),
        ('id_identities', '0001_initial'),
        ('id_access', '0002_viaccessitemrequest_account'),
        ('id_access', '0003_auto_20201123_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaccessitemrequest',
            name='ismember',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_item_requests', to='id_accounts.ViAccount'),
        ),
    ]
